/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ysomap;

import ysomap.runner.ConsoleRunner;

public class App {
    public static void main(String[] args) {
        new ConsoleRunner().run();
    }
}
